### ISSUE TITLE
Make this repository private?

### ISSUE THREAD

**Issue by johnousterhout** [abigail3306/Pintos#1]
I'm a Professor at Stanford, and I'm teaching an Operating Systems course that uses Pintos for its class projects. I'm writing because an automated search of GitHub identified this repository as possibly containing solutions for the Pintos programming projects. This is a problem for us, because it makes it very easy for students to cheat. Even if they just look at your solution, and don't copy it, that will still reduce the educational experience for them. If this repo does indeed contain Pintos solutions, would you be willing to take it down or at least make it private? If so, that would be a great help to us.

**Comment by abigail3306** [comment]
John,

Thanks for your note. Pintos was a big project for me and learned a lot. However I do not pay to have private git repositories and therefore cannot make it private. If you look through the code, this Pintos code is not complete and many files are still undone and unfinished. People who look at this project should not be able to finish their own project.

I also keep this partial code up for a portfolio of things that I worked on for employers. If I were to take it down on github, I would need to post it on another site so that I can have a portfolio of my work.
